//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracTurleri()
        {
            this.AracTurleriOtoPark = new HashSet<AracTurleriOtoPark>();
        }
    
        public int NumaraId { get; set; }
        public string Name { get; set; }
        public int StatusTypeId { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracTurleriOtoPark> AracTurleriOtoPark { get; set; }
    }
}
