//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracTurleriOtoPark
    {
        public int NumaraId { get; set; }
        public int AracTurleriNumaraId { get; set; }
        public int OtoParkNumaraId { get; set; }
        public int StatusTypeId { get; set; }
    
        public virtual AracTurleri AracTurleri { get; set; }
        public virtual OtoPark OtoPark { get; set; }
    }
}
