//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtoPark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtoPark()
        {
            this.AracTurleriOtoPark = new HashSet<AracTurleriOtoPark>();
        }
    
        public int NumaraId { get; set; }
        public string Name { get; set; }
        public int Kapasite { get; set; }
        public int StatusTypeId { get; set; }
        public string PARK_NAME { get; set; }
        public string LOCATION_NAME { get; set; }
        public string PARK_TYPE_ID { get; set; }
        public string PARK_TYPE_DESC { get; set; }
        public Nullable<int> CAPACITY_OF_PARK { get; set; }
        public string WORKING_TIME { get; set; }
        public string COUNTY_NAME { get; set; }
        public string rank { get; set; }
        public string coordinatesx { get; set; }
        public string coordinatesy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracTurleriOtoPark> AracTurleriOtoPark { get; set; }
    }
}
